# Generated by Django 4.1.3 on 2022-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=300)),
                ('content', models.TextField(max_length=1024)),
                ('photo', models.FileField(null=True, upload_to='photo/')),
                ('logo', models.FileField(null=True, upload_to='logo/')),
                ('site', models.URLField(null=True)),
            ],
        ),
    ]
